/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReadingListRouteImport } from './routes/reading-list'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSavedBooksRouteImport } from './routes/admin.saved-books'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as AdminBookDetailsBookIdRouteImport } from './routes/admin.book-details.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingListRoute = ReadingListRouteImport.update({
  id: '/reading-list',
  path: '/reading-list',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSavedBooksRoute = AdminSavedBooksRouteImport.update({
  id: '/saved-books',
  path: '/saved-books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookDetailsBookIdRoute = AdminBookDetailsBookIdRouteImport.update({
  id: '/book-details/$bookId',
  path: '/book-details/$bookId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reading-list': typeof ReadingListRoute
  '/register': typeof RegisterRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/saved-books': typeof AdminSavedBooksRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/book-details/$bookId': typeof AdminBookDetailsBookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reading-list': typeof ReadingListRoute
  '/register': typeof RegisterRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/saved-books': typeof AdminSavedBooksRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/book-details/$bookId': typeof AdminBookDetailsBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reading-list': typeof ReadingListRoute
  '/register': typeof RegisterRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/saved-books': typeof AdminSavedBooksRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/book-details/$bookId': typeof AdminBookDetailsBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/reading-list'
    | '/register'
    | '/admin/books'
    | '/admin/reviews'
    | '/admin/saved-books'
    | '/admin/users'
    | '/books/$bookId'
    | '/admin/'
    | '/admin/book-details/$bookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/reading-list'
    | '/register'
    | '/admin/books'
    | '/admin/reviews'
    | '/admin/saved-books'
    | '/admin/users'
    | '/books/$bookId'
    | '/admin'
    | '/admin/book-details/$bookId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/reading-list'
    | '/register'
    | '/admin/books'
    | '/admin/reviews'
    | '/admin/saved-books'
    | '/admin/users'
    | '/books/$bookId'
    | '/admin/'
    | '/admin/book-details/$bookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReadingListRoute: typeof ReadingListRoute
  RegisterRoute: typeof RegisterRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading-list': {
      id: '/reading-list'
      path: '/reading-list'
      fullPath: '/reading-list'
      preLoaderRoute: typeof ReadingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/saved-books': {
      id: '/admin/saved-books'
      path: '/saved-books'
      fullPath: '/admin/saved-books'
      preLoaderRoute: typeof AdminSavedBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/book-details/$bookId': {
      id: '/admin/book-details/$bookId'
      path: '/book-details/$bookId'
      fullPath: '/admin/book-details/$bookId'
      preLoaderRoute: typeof AdminBookDetailsBookIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSavedBooksRoute: typeof AdminSavedBooksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookDetailsBookIdRoute: typeof AdminBookDetailsBookIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSavedBooksRoute: AdminSavedBooksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookDetailsBookIdRoute: AdminBookDetailsBookIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReadingListRoute: ReadingListRoute,
  RegisterRoute: RegisterRoute,
  BooksBookIdRoute: BooksBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
